"""agent signing keys: agent-held keys, key history, signer key on records

Revision ID: a4d2c7e9b1f3
Revises: 7f8ed5bc5179
"""
from alembic import op
import sqlalchemy as sa

revision = "a4d2c7e9b1f3"
down_revision = "7f8ed5bc5179"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("agents", sa.Column("key_origin", sa.String(10)))
    op.add_column("delegation_hops", sa.Column("signer_public_key", sa.Text()))
    op.add_column("agent_actions", sa.Column("signer_public_key", sa.Text()))
    op.create_table(
        "agent_signing_keys",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("org_id", sa.Integer(), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("agent_id", sa.Integer(), sa.ForeignKey("agents.id", ondelete="CASCADE"), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(60), nullable=False),
        sa.Column("origin", sa.String(10), nullable=False),
        sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True)),
    )
    op.create_index("ix_agent_signing_keys_id", "agent_signing_keys", ["id"])
    op.create_index("ix_agent_signing_keys_org_id", "agent_signing_keys", ["org_id"])
    op.create_index("ix_agent_signing_keys_agent_id", "agent_signing_keys", ["agent_id"])
    # at most one current key per agent
    op.create_index("uq_agent_signing_keys_current", "agent_signing_keys", ["agent_id"], unique=True,
                    postgresql_where=sa.text("retired_at IS NULL"))

    # Every key that exists today was generated by the server at registration.
    op.execute("UPDATE agents SET key_origin = 'server' WHERE public_key IS NOT NULL")
    # Until now an agent's key never changed, so its current key is the one
    # that verified every signed record it has.
    op.execute(
        "UPDATE delegation_hops h SET signer_public_key = a.public_key FROM agents a "
        "WHERE a.id = h.from_agent_id AND h.signature IS NOT NULL AND h.verified "
        "AND h.signed_payload IS NOT NULL"
    )
    op.execute(
        "UPDATE agent_actions x SET signer_public_key = a.public_key FROM agents a "
        "WHERE a.id = x.agent_id AND x.signature IS NOT NULL AND x.signed_payload IS NOT NULL"
    )
    # History starts with the registration key. The fingerprint is
    # 'SHA256:' + unpadded base64 of SHA-256 over the raw 32 key bytes.
    op.execute(
        "INSERT INTO agent_signing_keys (org_id, agent_id, public_key, fingerprint, origin, created_by, created_at) "
        "SELECT org_id, id, public_key, "
        "'SHA256:' || rtrim(encode(sha256(decode(public_key, 'base64')), 'base64'), '=') , "
        "'server', owner_user_id, created_at FROM agents WHERE public_key IS NOT NULL"
    )


def downgrade():
    op.drop_index("uq_agent_signing_keys_current", table_name="agent_signing_keys")
    op.drop_index("ix_agent_signing_keys_agent_id", table_name="agent_signing_keys")
    op.drop_index("ix_agent_signing_keys_org_id", table_name="agent_signing_keys")
    op.drop_index("ix_agent_signing_keys_id", table_name="agent_signing_keys")
    op.drop_table("agent_signing_keys")
    op.drop_column("agent_actions", "signer_public_key")
    op.drop_column("delegation_hops", "signer_public_key")
    op.drop_column("agents", "key_origin")
